version: '3.8'
services:
  logstash:
    build: 
    environment:
       - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
       - monitoring.elasticsearch.hosts=http://elasticsearch:9200
    networks:
      - elastic
    ports:
      - 5044:5044
      - 9600:9600 
  elasticsearch:
    image: "robertrm/docker-elasticsearch-arm64:7.10.1"
    environment:
      - node.name=elasticsearch
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - elastic
    ports:
      - "9200:9200"
    volumes:
      - data01:/usr/share/elasticsearch/data
volumes:
  data01:
networks:
  elastic:
    driver: overlay
